# Chapter 5: Arrays

In [2]:
def even_odd(A):
    next_even, next_odd = 0, len(A) -1
    while next_even < next_odd:
        if A[next_even] % 2 == 0:
            next_even += 1 
        else:
            A[next_odd], A[next_even] = A[next_even], A[next_odd]
            next_odd -= 1
    return A

A = [0,5,6,2,7,9,4,0,6,8,5,2,4,6,87,23,88]
print A
print even_odd(A)

[0, 5, 6, 2, 7, 9, 4, 0, 6, 8, 5, 2, 4, 6, 87, 23, 88]
[0, 88, 6, 2, 6, 4, 4, 0, 6, 8, 2, 5, 9, 87, 23, 7, 5]


## 5.1 Dutch National Flag Problem
The quicksort algorithm for sorting arrays proceeds recursively -- it selects an elemnt (the pivot), reorders the array to make all the elements less than or equal to the pivot appear first, followed by all the elements greater than the pivot. The 2 subarrays are then sorted recursively. 

Write a program that takes an array A and an index i into A, and rearranges the elements such that all elements less than A[i] (the pivot) appear first, followed by elements equal to the pivot, followed by elements great than the pivot

In [10]:
def dutch_flag(A, i):
    next_pre, next_post, num_equal = 0, len(A) - 1, 0
    pivot = A[i]
    while next_pre + num_equal -1 < next_post:
        if A[next_pre + num_equal] == pivot:
            num_equal += 1
        elif A[next_pre + num_equal] < pivot:
            A[next_pre + num_equal], A[next_pre] = A[next_pre], A[next_pre + num_equal]
            next_pre += 1
        else:
            A[next_pre + num_equal], A[next_post] = A[next_post], A[next_pre + num_equal]
            next_post -= 1
    return A

A = [1,0,2,0,1,2,1,0,2,1,0,2,2,2,1,0]
print dutch_flag(A,0)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


Variant: Assuming that keys take one of 3 values, reorder the array so that all objects with the same key appear together. Order of the variants isn't important, Use O(1) space and O(n) time

In [42]:
import collections
def dutch_flag_3_elements(A):
    keyTally = collections.Counter()
    for element in A:
        keyTally[element] += 1
    pos = 0
    for item in keyTally:
        A[pos:pos + keyTally[item]] = [item] * keyTally[item] 
        pos += keyTally[item]
    return A

A = [1,0,2,0,1,2,1,0,2,1,0,2,2,2,1,0]
print dutch_flag_3_elements(A)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


## 5.2 Increment an Arbitrary-Precision Integer
Write a program which takes as input an array of digits encoding a decimal integer D and updates the array to represent the integer D + 1. For example, if the input is <1,2,9> then you should update the array to <1,3,0>

In [66]:
def increment_int_array(D):
    carry = 1
    pos = len(D) - 1
    while carry > 0 and pos >= 0:
        D[pos] += carry
        if D[pos] > 9:
            carry = D[pos] / 10
            D[pos] = D[pos] - 10 * carry
            pos -= 1
        else:
            carry = 0 
            break
    if (pos <= 0 and carry > 0):
        D.insert(0, carry)
    return D

assert(increment_int_array([1,2,9]) == [1,3,0])
assert(increment_int_array([9,9,9]) == [1,0,0,0])
assert(increment_int_array([1,0,2]) == [1,0,3])

## 5.3 Multiply Two Arbitrary-Precision Integers
Write a program that takes two arrays representing integers, and returns an integer representing their product. 
[1,9,3,7,0,7,7,2,1] * [-7,6,1,8,3,8,2,5,7,2,8,7] = [-1,4,7,5,7,3,9,5,2,5,8,9,6,7,6,4,1,2,9,2,7]

In [18]:
def multiply_arrays(A,B):
    if (A[0] < 0 or B[0] < 0):
        sign = -1
    else:
        sign = 1
    A[0], B[0] = abs(A[0]), abs(B[0])
    result = [0]*(len(A) + len(B))
    for iA in reversed(range(len(A))):
        for iB in reversed(range(len(B))):
            result[iA + iB + 1] += A[iA] * B[iB]
            result[iA + iB] += result[iA + iB + 1] // 10
            result[iA + iB + 1] %= 10 
    result[0] *= sign * result[0]
    return result

assert(multiply_arrays([1,9,3,7,0,7,7,2,1], [-7,6,1,8,3,8,2,5,7,2,8,7]) == [-1,4,7,5,7,3,9,5,2,5,8,9,6,7,6,4,1,2,9,2,7])
assert(multiply_arrays([2],[5]) == [1,0])
assert(multiply_arrays([2,0,0,2],[5,9,9,9,9,8]) == [1, 2, 0, 1, 1, 9, 5, 9, 9, 6])

## 5.5 Delete Duplicate Elements
Write a program to delete duplicate elements in an area and return the number of unique elements

In [29]:
def delete_dups(A):
    num_uniques = 0
    current = None
    for i in range(len(A)):
        if A[i] != current:
            current = A[i]
            A[num_uniques] = current
            num_uniques += 1
    A[num_uniques:len(A)] = [0] * ((len(A)) - num_uniques - 1)
    return num_uniques

test1 = [1,1,2,2,2,3,4,4,5,5,5,6,6,7,7,7,7,8]
assert(delete_dups(test1) == 8)
assert(test == [1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0])

test2 = [0,1,2,3,3,3,3,3,4,4,5,5,5,5,5,5,6,6,6,6,7,7,7,7,9,9,9,10,11,11,15,15,128,129]
assert(delete_dups(test2) == 14)
assert(test2 == [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 15, 128, 129, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 5.6 Buy and Sell a Stock Once
Write a program that returns the most you could make off by buying and selling a stock at the optimal times given a list of time ordered stock prices. 

Example: [310, 315, 275, 295, 260, 270, 290, 230, 255, 250] returns 30 

In [39]:
def stock_best(S):
    max_diff = 0
    current_max = 0
    for i in reversed(range(len(S))):
        diff = current_max - S[i]
        if diff > max_diff:
            max_diff = diff
        if S[i] > current_max:
            current_max = S[i]
    return max_diff

assert(stock_best([310, 315, 275, 295, 260, 270, 290, 230, 255, 250]) == 30)
assert(stock_best([310, 315, 275, 295, 260, 270, 230, 250, 240]) == 20)

## Enumerate All Primes to N
A natural number is called a prime if it is bigger than 1 and has no divisors other than 1 and itself.

Write a program that takes an integer argument and returns all the primes between 1 and that integer. For example, if the input is 18, you should return <2,3,5,7,11,13,17>

In [102]:
def all_primes(n):
    '''return all primes between 1 and n
       input: n is an integer greater than 1
       output: list of integers that are prime between 1 and n
    '''
    prime_boolean = [True] * ((n)/2)
    primes = [2]
    for i in range(3, n + 1,2):
        if prime_boolean[(i - 3) / 2]:
            primes.append(i)
            for j in range(i, n/i + 1,2):
                prime_boolean[((i * j) - 2)/2] = False
    return primes
                
assert(all_primes(19) == [2, 3, 5, 7, 11, 13, 17, 19])

## Permute the Elements of an Array
Given an array A of n elements and a permutation P, apply P to A
example the permutation [2,0,1,3] applied to A = [a,b,c,d] is [b,c,a,d]

In [119]:
def permute_array(orig, perm):
    for i, i_p in enumerate(perm):
        temp_i = i
        new_item = orig[i]
        while (perm[temp_i] >= 0):
            new_item, orig[perm[temp_i]] = orig[perm[temp_i]], new_item
            perm[temp_i], temp_i = -1, perm[temp_i]
    return orig

assert(permute_array(['a','b','c','d'], [2,0,1,3]) == ['b', 'c', 'a', 'd'])
assert(permute_array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], [2,1,0,4,6,5,3]) == ['c', 'b', 'a', 'g', 'd', 'f', 'e'])

## Sample Offline Data
This problem is motivated by the need for a company to select a random subset of its customers to roll out a new feature to. 
Implement an algorithm that takes as input an array of distinct elements and a size, and returns a subset of the given size of the array elements. All subsets should be equally likely. Return the result in input array itself

In [156]:
import random
import math
def sample_offline(array, n):
    for i in range(n):
        keep = random.randint(i,len(array)-1)
        array[i], array[keep] = array[keep], array[i]
    return array[0:n]

print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)
print sample_offline([0,1,2,3,4,5,6,4,5,6,7,8,9,1,2,3,4,5], 5)


[2, 4, 6, 3, 4]
[1, 5, 5, 0, 4]
[3, 5, 6, 7, 2]
[3, 3, 2, 8, 5]
[6, 4, 9, 4, 5]
[7, 4, 6, 1, 5]
[5, 1, 4, 5, 4]
[6, 2, 8, 7, 5]
[5, 6, 4, 4, 1]


## 5.15 Compute a Random Subset
Write a program that takes a positive integer n and a size k <= n and returns a size-k subset of [0,1,2,....,n-1]. The subset should be represented as an array. 

In [167]:
import random
def random_subset(n,k):
    A = {}
    for i in range(k + 1):
        perm = random.randint(i,n-1)
        new_map = A.get(perm, perm)
        new_i = A.get(i,i)
        A[i] = new_map
        A[perm] = new_i
    return [A[i] for i in range(k)]

print random_subset(10,4)        
print random_subset(10,4)        
print random_subset(10,4)        
print random_subset(10,4)        

[6, 3, 9, 8]
[7, 5, 2, 6]
[0, 2, 6, 8]
[9, 7, 0, 8]


## The Sudoku Checker
Check whether a 9x9 2D array representing a partially completed Sudoku is valid. Specifically check that no row, column, or 3x3 2D subarray contains duplicates. 0 means empty

In [217]:
import numpy as np

def dup_check(block):
    block = list(filter(lambda x: x != 0, block))
    return len(list(block)) > len(set(list(block)))
    

def sudoku_check(A):
    for i in range(9):
        if dup_check(A[0,:]) or dup_check(A[:,0]):
            return False
    for i in range(0,7,3):
        for j in range(0,7,3):
            if dup_check(A[i:i+3,j:j+3].flatten()):
                return False
    return True
    
A = np.array(
    [[0,0,0,1,2,0,3,0,4],
     [0,0,0,0,0,0,0,0,5],
     [0,0,0,6,3,0,2,0,1],
     [0,0,0,0,4,0,5,0,0],
     [0,0,0,0,5,0,6,0,0],
     [0,0,0,3,6,0,7,0,0],
     [0,0,0,7,0,0,8,0,0],
     [0,0,0,8,0,0,9,0,0],
     [0,0,0,9,0,0,0,0,0]])
print sudoku_check(A)

True


## 5.18 Compute the Spiral Ordering of a 2D Array
Write a program which takes an nxn 2D array and returns the spiral ordering of the array

In [261]:
def outer_spiral(full):
    outer = list(full[0,:-1]) 
    outer += list(full[:-1,-1])
    outer += list(full[-1,-1:0:-1]) 
    outer += list(full[-1:0:-1,0])
    return outer
    

def print_spiral(A):
    final = []
    while len(A.flatten()) > 0:
        final += outer_spiral(A)
        A = A[1:-1,1:-1]    
    return final

A = np.array([
        [0,1,2,3],
        [4,5,6,7],
        [8,9,10,11],
        [12,13,14,15]
    ])
assert(print_spiral(A) == [0, 1, 2, 3, 7, 11, 15, 14, 13, 12, 8, 4, 5, 6, 10, 9])

B = A = np.array([
        [0,1,2,3],
        [4,5,6,7],
        [8,9,10,11],
        [12,13,14,15],
        [16,17,18,19],
        [20,21,22,23],
        [24,25,26,27]
    ])
assert(print_spiral(A) == [0, 1, 2, 3, 7, 11, 15, 19, 
                           23, 27, 26, 25, 24, 20, 16, 
                           12, 8, 4, 5, 6, 10, 14, 18, 
                           22, 21, 17, 13, 9])


## 5.19 Rotate a 2D Array
Write a function that takes as input an nxn 2D array, and rotates the array by 90 degrees clockwise

In [289]:
def rotate_outer(A, i):
    A[0,0], A[0,-1], A[-1,-1], A[-1, 0] = A[-1,0], A[0,0], A[0,-1], A[-1,-1]
    
def rotate_array90(A):
    l = len(A[0]) - 1
    for i in range(l - 1):
        for j in range(l - 1):
            A[i,j], A[j,l-i], A[l-i, l-j], A[l-j, i] = A[l-j, i], A[i,j], A[j,l-i], A[l-i, l-j]        
            print A
    return A

A = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
    ])
print rotate_array90(A)

[[13  2  3  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [16 14 15  4]]
[[13  9  3  1]
 [ 5  6  7  2]
 [15 10 11 12]
 [16 14  8  4]]
[[13  9  5  1]
 [14  6  7  2]
 [15 10 11  3]
 [16 12  8  4]]
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
